name: DNS Stack Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - '!README.md'

concurrency:
  group: dns-stack-tests-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Generate test tag
      id: tag
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        CLEAN_BRANCH_NAME=$(echo $BRANCH_NAME | tr '/' '-')
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        echo "tag=${CLEAN_BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_OUTPUT

    - name: Build test image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: dns-stack-test:${{ steps.tag.outputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Start test container
      run: |
        # Set system limits on the host
        sudo sysctl -w net.core.rmem_max=8388608
        sudo sysctl -w net.core.wmem_max=8388608
        
        docker run -d --name dns-stack-test \
          -v ${{ github.workspace }}/tests:/tests \
          dns-stack-test:${{ steps.tag.outputs.tag }}

    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to initialize..."
        sleep 25  # Increased wait time for services
        docker ps
        docker logs dns-stack-test

    - name: Set permissions on test scripts
      run: |
        chmod +x ./tests/test_unbound.sh
        chmod +x ./tests/test_redis.sh
        chmod +x ./tests/test_adguard.sh

    - name: Run Unbound DNS tests
      id: unbound
      run: docker exec dns-stack-test /tests/test_unbound.sh
      
    - name: Run Redis tests
      id: redis
      run: docker exec dns-stack-test /tests/test_redis.sh
      
    - name: Run AdGuard Home tests
      id: adguard
      run: docker exec dns-stack-test /tests/test_adguard.sh

    - name: Test Summary
      if: always()
      run: |
        echo "Test Results Summary:"
        echo "===================="
        echo "Unbound DNS: ${{ steps.unbound.outcome }}"
        echo "Redis: ${{ steps.redis.outcome }}"
        echo "AdGuard Home: ${{ steps.adguard.outcome }}"

    - name: Clean up
      if: always()
      run: |
        docker stop dns-stack-test || true
        docker rm dns-stack-test || true
