name: DNS Stack Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Generate test tag
      id: tag
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        CLEAN_BRANCH_NAME=$(echo $BRANCH_NAME | tr '/' '-')
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        echo "tag=${CLEAN_BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_OUTPUT

    - name: Build test image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: dns-stack-test:${{ steps.tag.outputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Start test container
      run: |
        # Set system limits on the host
        sudo sysctl -w net.core.rmem_max=8388608
        sudo sysctl -w net.core.wmem_max=8388608
        
        docker run -d --name dns-stack-test \
          --privileged \
          -p 5353:53/tcp \
          -p 5353:53/udp \
          -p 3001:3000 \
          -p 5335:5335 \
          -p 6380:6379 \
          dns-stack-test:${{ steps.tag.outputs.tag }}

    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to initialize..."
        sleep 45  # Increased wait time for services
        docker ps
        docker logs dns-stack-test

    - name: Copy and prepare test scripts
      run: |
        # Create test directory in container
        docker exec dns-stack-test mkdir -p /tests
        
        # Copy test files
        docker cp ./tests/test_unbound.sh dns-stack-test:/tests/
        docker cp ./tests/test_redis.sh dns-stack-test:/tests/
        docker cp ./tests/test_adguard.sh dns-stack-test:/tests/
        
        # Set permissions
        docker exec dns-stack-test chmod +x /tests/test_*.sh

    - name: Run Unbound DNS tests
      id: unbound
      run: docker exec dns-stack-test /tests/test_unbound.sh
      
    - name: Run Redis tests
      id: redis
      run: docker exec dns-stack-test /tests/test_redis.sh
      
    - name: Run AdGuard Home tests
      id: adguard
      run: docker exec dns-stack-test /tests/test_adguard.sh

    - name: Test Summary
      if: always()
      run: |
        echo "Test Results Summary:"
        echo "===================="
        echo "Unbound DNS: ${{ steps.unbound.outcome }}"
        echo "Redis: ${{ steps.redis.outcome }}"
        echo "AdGuard Home: ${{ steps.adguard.outcome }}"

    - name: Clean up
      if: always()
      run: |
        docker stop dns-stack-test || true
        docker rm dns-stack-test || true
