name: 1. Daily Version Check

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Get Latest Versions
      id: versions
      run: |
        UNBOUND_VERSION=$(curl -s https://nlnetlabs.nl/downloads/unbound/ | grep -oP 'unbound-\K[0-9]+\.[0-9]+\.[0-9]+(?=\.tar\.gz)' | sort -V | tail -n1)
        ADGUARD_VERSION=$(curl -s https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest | jq -r .tag_name)
        
        CURRENT_UNBOUND=$(grep "ARG UNBOUND_VERSION=" Dockerfile | cut -d'"' -f2)
        CURRENT_ADGUARD=$(grep "ARG ADGUARD_VERSION=" Dockerfile | cut -d'"' -f2)
        
        echo "UNBOUND_VERSION=${UNBOUND_VERSION}" >> $GITHUB_ENV
        echo "ADGUARD_VERSION=${ADGUARD_VERSION}" >> $GITHUB_ENV
        echo "CURRENT_UNBOUND=${CURRENT_UNBOUND}" >> $GITHUB_ENV
        echo "CURRENT_ADGUARD=${CURRENT_ADGUARD}" >> $GITHUB_ENV
        
        if [ "${CURRENT_UNBOUND}" = "${UNBOUND_VERSION}" ] && [ "${CURRENT_ADGUARD}" = "${ADGUARD_VERSION}" ]; then
          echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
        else
          echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
        fi

    - name: Create Update Branch
      if: env.UPDATE_NEEDED == 'true'
      run: |
        BRANCH_NAME="version-update-${GITHUB_SHA::8}"
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git checkout -b $BRANCH_NAME
        
        sed -i.bak "s|ARG UNBOUND_VERSION=.*|ARG UNBOUND_VERSION=\"${UNBOUND_VERSION}\"|" Dockerfile
        sed -i.bak "s|ARG ADGUARD_VERSION=.*|ARG ADGUARD_VERSION=\"${ADGUARD_VERSION}\"|" Dockerfile
        rm -f Dockerfile.bak
        
        git add Dockerfile
        git commit -m "chore: update Unbound to ${UNBOUND_VERSION} and AdGuard to ${ADGUARD_VERSION}"
        git push origin $BRANCH_NAME
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

    - name: Create Pull Request
      if: env.UPDATE_NEEDED == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        title: 'chore: update component versions'
        body: |
          Automated version update:
          - Unbound: ${{ env.CURRENT_UNBOUND }} → ${{ env.UNBOUND_VERSION }}
          - AdGuard: ${{ env.CURRENT_ADGUARD }} → ${{ env.ADGUARD_VERSION }}
        branch: ${{ env.BRANCH_NAME }}
        base: main
        labels: version-update
